### PR TITLE
Make telnetd autoexec and run docker instance in daemon mode

### PR DESCRIPTION
**Pull request by chadillac**

### CODE REVIEW

**Comment by chadillac** [comment]
automated FS mapping for Overlay2 storage driver as well (devicemapper was giving me headaches)

**Comment by compoterhacker** [comment]
Rad, I'm going to merge this now, but update it later with a more general approach(along with other much needed updates), as there's a whole slew of differences in filesystem mount points that I've run into.

**Comment by chadillac** [comment]
I actually have been working on another setup that is wrapped around `mehrai` and was using `devicemapper`, ran into the same failure to properly map issue, used the same solution fwiw.

**Comment by chadillac** [comment]
@d1rt_diggler on twitter, ping me, we should chat ;)

**Comment by compoterhacker** [comment]
Sounds good to me! pinged ya

**Pull request merged**
